server:
  port: 8443
  ssl:
    bundle: server

spring:
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: classpath:certs/server-a.crt
            private-key: classpath:certs/server-a.key
          truststore:
            certificate: classpath:certs/ca.crt
        client:
          truststore:
            certificate: classpath:certs/ca.crt

app:
  server-b:
    url: https://localhost:9443

logging:
  level:
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always