server:
  port: 9443
  ssl:
    bundle: server

spring:
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: classpath:certs/server-b.crt
            private-key: classpath:certs/server-b.key
          truststore:
            certificate: classpath:certs/ca.crt
        client:
          truststore:
            certificate: classpath:certs/ca.crt

app:
  server-a:
    url: https://localhost:8443

logging:
  level:
    com.example: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always